import type { Vendor, User } from './types';
import { PlaceHolderImages } from './placeholder-images';

export const CATEGORIES = [
    'Restaurant',
    'Cafe',
    'Bakery',
    'Butcher',
    'Auto Repair',
    'Pet Grooming',
    'Bookstore',
    'Clothing',
    'Florist',
    'Grocery',
    'Hardware',
    'Salon',
];

export const VENDORS: Vendor[] = [
    {
        id: '1',
        name: 'Golden Gate Grub',
        description: 'Classic American diner with a modern twist, serving breakfast all day.',
        image: PlaceHolderImages.find(p => p.id === 'vendor-1')?.imageUrl || '',
        categories: ['Restaurant'],
        rating: 4.5,
        reviews: 120,
        location: { lat: 37.78, lng: -122.41 },
        address: '123 Market St, San Francisco, CA',
        phone: '415-555-1234',
        hours: '7am - 10pm',
    },
    {
        id: '2',
        name: 'The Daily Bean',
        description: 'Cozy coffee shop with artisanal pastries and locally roasted coffee.',
        image: PlaceHolderImages.find(p => p.id === 'vendor-2')?.imageUrl || '',
        categories: ['Cafe', 'Bakery'],
        rating: 4.8,
        reviews: 250,
        location: { lat: 37.77, lng: -122.42 },
        address: '456 Mission St, San Francisco, CA',
        phone: '415-555-5678',
        hours: '6am - 6pm',
    },
    {
        id: '3',
        name: 'City Lights Books',
        description: 'Iconic independent bookstore with a vast collection of literature and poetry.',
        image: PlaceHolderImages.find(p => p.id === 'vendor-3')?.imageUrl || '',
        categories: ['Bookstore'],
        rating: 4.9,
        reviews: 500,
        location: { lat: 37.79, lng: -122.40 },
        address: '261 Columbus Ave, San Francisco, CA',
        phone: '415-362-8193',
        hours: '10am - 10pm',
    },
    {
        id: '4',
        name: 'Precision Auto',
        description: 'Family-owned auto repair shop with honest service and fair prices.',
        image: PlaceHolderImages.find(p => p.id === 'vendor-4')?.imageUrl || '',
        categories: ['Auto Repair'],
        rating: 4.7,
        reviews: 85,
        location: { lat: 37.76, lng: -122.43 },
        address: '789 Valencia St, San Francisco, CA',
        phone: '415-555-9012',
        hours: '8am - 5pm',
    },
    {
        id: '5',
        name: 'Pawsitively Perfect',
        description: 'Professional pet grooming services for dogs and cats of all sizes.',
        image: PlaceHolderImages.find(p => p.id === 'vendor-5')?.imageUrl || '',
        categories: ['Pet Grooming'],
        rating: 4.9,
        reviews: 150,
        location: { lat: 37.75, lng: -122.44 },
        address: '101 Castro St, San Francisco, CA',
        phone: '415-555-3456',
        hours: '9am - 6pm',
    },
    {
        id: '6',
        name: 'Bloom & Bud',
        description: 'Charming florist with fresh, beautiful arrangements for any occasion.',
        image: PlaceHolderImages.find(p => p.id === 'vendor-6')?.imageUrl || '',
        categories: ['Florist'],
        rating: 4.6,
        reviews: 70,
        location: { lat: 37.78, lng: -122.45 },
        address: '321 Hayes St, San Francisco, CA',
        phone: '415-555-7890',
        hours: '10am - 7pm',
    },
    {
        id: '7',
        name: 'The Organic Stop',
        description: 'Neighborhood grocery store specializing in local and organic produce.',
        image: PlaceHolderImages.find(p => p.id === 'vendor-7')?.imageUrl || '',
        categories: ['Grocery'],
        rating: 4.4,
        reviews: 95,
        location: { lat: 37.74, lng: -122.42 },
        address: '555 Cortland Ave, San Francisco, CA',
        phone: '415-555-2345',
        hours: '8am - 9pm',
    },
    {
        id: '8',
        name: 'Style Thread',
        description: 'Modern boutique featuring independent designers and contemporary fashion.',
        image: PlaceHolderImages.find(p => p.id === 'vendor-8')?.imageUrl || '',
        categories: ['Clothing'],
        rating: 4.7,
        reviews: 110,
        location: { lat: 37.77, lng: -122.43 },
        address: '888 Haight St, San Francisco, CA',
        phone: '415-555-6789',
        hours: '11am - 7pm',
    },
    {
        id: '9',
        name: 'The Cut Above',
        description: 'Upscale hair salon offering a full range of styling and color services.',
        image: PlaceHolderImages.find(p => p.id === 'vendor-9')?.imageUrl || '',
        categories: ['Salon'],
        rating: 4.8,
        reviews: 180,
        location: { lat: 37.79, lng: -122.41 },
        address: '777 Sacramento St, San Francisco, CA',
        phone: '415-555-1122',
        hours: '9am - 8pm',
    },
    {
        id: '10',
        name: "Art's Hardware",
        description: 'A friendly, old-school hardware store that has everything you need.',
        image: PlaceHolderImages.find(p => p.id === 'vendor-10')?.imageUrl || '',
        categories: ['Hardware'],
        rating: 4.6,
        reviews: 60,
        location: { lat: 37.76, lng: -122.46 },
        address: '999 Irving St, San Francisco, CA',
        phone: '415-555-3344',
        hours: '7am - 7pm',
    },
    {
        id: '11',
        name: 'Sourdough & Co.',
        description: 'Famous for its sourdough bread bowls and delicious sandwiches.',
        image: PlaceHolderImages.find(p => p.id === 'vendor-11')?.imageUrl || '',
        categories: ['Bakery', 'Restaurant'],
        rating: 4.7,
        reviews: 210,
        location: { lat: 37.80, lng: -122.41 },
        address: 'Pier 39, San Francisco, CA',
        phone: '415-555-1111',
        hours: '11am - 9pm',
    }
];

export const USERS: User[] = [
    { id: '1', name: 'Alice Johnson', email: 'alice@example.com', role: 'user', joinedDate: '2023-01-15' },
    { id: '2', name: 'Bob Williams', email: 'bob@example.com', role: 'user', joinedDate: '2023-02-20' },
    { id: '3', name: 'Charlie Brown', email: 'charlie@example.com', role: 'user', joinedDate: '2023-03-10' },
    { id: '4', name: 'Diana Miller', email: 'diana@example.com', role: 'vendor', joinedDate: '2023-04-05' },
    { id: '5', name: 'Ethan Davis', email: 'ethan@example.com', role: 'admin', joinedDate: '2023-01-01' },
    { id: '6', name: 'Fiona Garcia', email: 'fiona@example.com', role: 'vendor', joinedDate: '2023-05-22' },
];
